[package]
name = "body_sculpting"
version = "0.1.0"
authors = ["Thomas Markiewicz <tomek@liberty.one>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.6.0"
log = "0.4.8"
quote = "1.0.7"
